INSERT INTO public.goods (id, name, priority) VALUES (24, 'Одуванчики', 0);
INSERT INTO public.goods (id, name, priority) VALUES (8, 'Паучьи листья', 0.015);
INSERT INTO public.goods (id, name, priority) VALUES (1, 'Каприфоль', 0.017);
INSERT INTO public.goods (id, name, priority) VALUES (20, 'Грибы-шибальцы', 0.03);
INSERT INTO public.goods (id, name, priority) VALUES (9, 'Лаванда', 0.023);
INSERT INTO public.goods (id, name, priority) VALUES (2, 'Волшебная палочка из виноградной лозы', 0.033);
INSERT INTO public.goods (id, name, priority) VALUES (6, 'Полынь горькая', 0.034);
INSERT INTO public.goods (id, name, priority) VALUES (19, 'Серебряница', 0.075);
INSERT INTO public.goods (id, name, priority) VALUES (15, 'Мышехвост', 0.032);
INSERT INTO public.goods (id, name, priority) VALUES (444, 'Волшебная палочка', 0.079);
INSERT INTO public.goods (id, name, priority) VALUES (14, 'Ласточкина трава', 0.067);
INSERT INTO public.goods (id, name, priority) VALUES (18, 'Лекарство от ликантропии', 0.041);
INSERT INTO public.goods (id, name, priority) VALUES (17, 'Кровь дракона', 0.013);
INSERT INTO public.goods (id, name, priority) VALUES (10, 'Вороний глаз', 0.016);
INSERT INTO public.goods (id, name, priority) VALUES (12, 'Волкобой', 0.088);
INSERT INTO public.goods (id, name, priority) VALUES (22, 'Волкобой', 0.06);
INSERT INTO public.goods (id, name, priority) VALUES (4, 'Волшебная палочка из грецкого ореха с жилой дракона', 0.026);
INSERT INTO public.goods (id, name, priority) VALUES (5, 'Волшебная палочка из тиса', 0.07);
INSERT INTO public.goods (id, name, priority) VALUES (21, 'Одуванчики', 0.054);
INSERT INTO public.goods (id, name, priority) VALUES (16, 'Горьяд', 0.047);
INSERT INTO public.goods (id, name, priority) VALUES (3, 'Волшебная палочка из черного дерева с жилой дракона', 0.012);
INSERT INTO public.goods (id, name, priority) VALUES (13, 'Голубой цветок лотоса', 0.05);
INSERT INTO public.goods (id, name, priority) VALUES (23, 'Волшебная палочка из виноградной лозы', 0);