INSERT INTO public.goods (id, name, priority) VALUES (3, 'Волшебная палочка из черного дерева с жилой дракона', 0.67);
INSERT INTO public.goods (id, name, priority) VALUES (20, 'Грибы-шибальцы', 0.9);
INSERT INTO public.goods (id, name, priority) VALUES (10, 'Вороний глаз', 0.16);
INSERT INTO public.goods (id, name, priority) VALUES (15, 'Мышехвост', 0.32);
INSERT INTO public.goods (id, name, priority) VALUES (17, 'Кровь дракона', 0.13);
INSERT INTO public.goods (id, name, priority) VALUES (19, 'Серебряница', 0.75);
INSERT INTO public.goods (id, name, priority) VALUES (14, 'Ласточкина трава', 0.67);
INSERT INTO public.goods (id, name, priority) VALUES (21, 'Одуванчики', 0.54);
INSERT INTO public.goods (id, name, priority) VALUES (1, 'Каприфоль', 0.17);
INSERT INTO public.goods (id, name, priority) VALUES (22, 'Волкобой', 0.6);
INSERT INTO public.goods (id, name, priority) VALUES (4, 'Волшебная палочка из грецкого ореха с жилой дракона', 0.26);
INSERT INTO public.goods (id, name, priority) VALUES (6, 'Полынь горькая', 0.34);
INSERT INTO public.goods (id, name, priority) VALUES (16, 'Горьяд', 0.47);
INSERT INTO public.goods (id, name, priority) VALUES (18, 'Лекарство от ликантропии', 0.41);
INSERT INTO public.goods (id, name, priority) VALUES (13, 'Голубой цветок лотоса', 0.5);
INSERT INTO public.goods (id, name, priority) VALUES (444, 'Волшебная палочка', 0.79);
INSERT INTO public.goods (id, name, priority) VALUES (9, 'Лаванда', 0.23);
INSERT INTO public.goods (id, name, priority) VALUES (12, 'Волкобой', 0.88);
INSERT INTO public.goods (id, name, priority) VALUES (8, 'Паучьи листья', 0.15);
INSERT INTO public.goods (id, name, priority) VALUES (5, 'Волшебная палочка из тиса', 0.7);
INSERT INTO public.goods (id, name, priority) VALUES (2, 'Волшебная палочка из виноградной лозы', 0.33);
INSERT INTO public.goods (id, name, priority) VALUES (23, 'dgs', 0);